### ISSUE TITLE
Displaying a automaton that just got standardized displays the old one

### ISSUE THREAD

**Issue by mattelothere** [hickatheworld/SM402I-Project#15]
As example, chose to work on automaton 5
![image](https://github.com/hickatheworld/SM402I-Project/assets/90071735/2f10453d-a004-4004-ad00-c68cd71c8c67)
Because it is not standard you can choose to standardize it :
![image](https://github.com/hickatheworld/SM402I-Project/assets/90071735/ac03890d-7f37-44ae-a487-1fe872a692e2)
Standardazation works just fine without any errors :
![image](https://github.com/hickatheworld/SM402I-Project/assets/90071735/aadef0bb-8218-484a-b26f-22bcf72213ac)

But nothing seems to have changed when displaying the old and new version

Before standardization :
![image](https://github.com/hickatheworld/SM402I-Project/assets/90071735/3b28f292-cc75-4741-9a94-fde75a4badee)

After :
![image](https://github.com/hickatheworld/SM402I-Project/assets/90071735/3fd5eace-3901-4909-8249-59c0fbbb0a28)

**Comment by mattelothere** [comment]
I think it is bugging because the "display automaton" function always retrieves information from the automata.json file

Maybe once we are done with standardizing we should save it as src/automata/modified/INT-1-5-automaton.txt

And change the display_automaton call to first try to retrieve the automaton information from the src/automata/modified folder, and if we don't find it, go to the automata.json file. (without forgeting to notify the user)

**Comment by mattelothere** [comment]
Still no fix

**Comment by campoceblo** [comment]
Fixed,
I choose to print directly after the standarisation, thus i created a new automata_SFA wich is the output of stan.standardize(automata_dict)
