### ISSUE TITLE
.txt of the automata should be in the same folder as the code files

### ISSUE THREAD

**Issue by mattelothere** [hickatheworld/SM402I-Project#21]
By the project instructions
![image](https://github.com/hickatheworld/SM402I-Project/assets/90071735/76ac7e33-e517-4922-8125-8c9d6db2da13)

**Comment by leflon** [comment]
c'est le cas

**Comment by mattelothere** [comment]
je crois pas - j'ai pris ce screen sur la branche feat-determinization mais c'est la meme sur master
![image](https://github.com/hickatheworld/SM402I-Project/assets/90071735/a1d611fe-c8ef-46b9-aef5-8ad99d6acc6f)
les .txt sont dans un sous-dossier, je pense pas que ça compte

**Comment by leflon** [comment]
si ça compte arrête de te prendre la têt
